---
rvm:
  - "2.0.0"
  - "1.9.3"
  - "1.9.2"
#  - jruby-19mode
#  - rbx-19mode

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS coinpunk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database coinpunk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS coinpunk_test'; fi"
